# Generated by Django 5.0.4 on 2024-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='image',
            field=models.FilePathField(path='..\\..\\frontend\\public\\assets\\svgs'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_rating'),
        ),
    ]
