# Generated by Django 5.0.4 on 2024-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_achivement_image_rating_unique_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='image',
            field=models.FilePathField(path='../../frontend/public/assets/svgs'),
        ),
        migrations.AlterModelTable(
            name='achivement',
            table=None,
        ),
    ]
