# Generated by Django 5.0.4 on 2024-06-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_achivement_image_alter_achivement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achivement',
            table='Achivement',
        ),
    ]
